kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rbd
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/rbd
parameters:
  monitors: 10.125.224.26:6789
  adminId: admin
  adminSecretName: ceph-admin
  adminSecretNamespace: default
  pool: k8s
  userId: admin
  userSecretName: ceph-admin
  fsType: xfs  # fsType: ext4
  imageFormat: "1" # imageFormat: "2"
  # imageFeatures: "layering"