apiVersion: v1
kind: PersistentVolume
metadata:
  name: rbd
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    monitors:
      - '10.123.102.70:6789,10.123.102.71:6789,10.123.102.72:6789'
    pool: k8s
    image: pv
    user: admin
    secretRef:
      name: cephh-admin
    fsType: xfs
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle