apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  labels:
    app: wordpress
spec:
  storageClassName: wordpress-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
