apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset1
  labels:
    label-rep: value-rep
spec:
  replicas: 2
  selector:
    matchLabels:
      label-pod: value-pod
  template:
    metadata:
      labels:
        label-pod: value-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
