apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment2-hpa
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: ct-nginx
          image: nginx:1.9.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  name: deployment2-hpa-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80
