apiVersion: batch/v1
kind: Job
metadata:
  name: job1
spec:
  template:
    metadata:
      name: busyboxplus
    spec:
      restartPolicy: Never
      containers:
        - name: ct-busyboxplus
          image: radial/busyboxplus:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "echo hello"]
