apiVersion: batch/v1
kind: Job
metadata:
  name: job2
spec:
  template:
    metadata:
      name: pi
    spec:
      restartPolicy: Never
      containers:
        - name: ct-pi
          image: perl:latest
          imagePullPolicy: IfNotPresent
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(20)"]
