# apiVersion: batch/v1beta1 # Before 1.21
apiVersion: batch/v1 # After 1.21
kind: CronJob
metadata:
  name: cronjob1 
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ct-busyboxplus
              image: radial/busyboxplus
              imagePullPolicy: IfNotPresent
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster