apiVersion: v1
kind: Pod
metadata:
  name: nginx-taint1
  labels:
    app: nginx-taint1
spec:
  containers:
  - name: nginx-taint1
    image: nginx
    resources:
      limits:
        cpu: 30m
        memory: 20Mi
      requests:
        cpu: 20m
        memory: 10Mi
  tolerations:
  - key: taint1
    value: test2
    operator: Equal
    effect: NoSchedule
