apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: pod4-liveness-cmd
spec:
  containers:
    - name: liveness
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'touch /tmp/healthy; sleep 20; rm -rf /tmp/healthy; sleep 20']
      livenessProbe:
        exec:
          command: ['sh', '-c', 'cat /tmp/healthy']
        initialDelaySeconds: 5
        periodSeconds: 5
