apiVersion: v1
kind: Pod
metadata:
  name: pod7-node-selector
  labels:
    env: test
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: ssd
