apiVersion: v1
kind: Pod
metadata:
  name: pod8-initcontainer
  labels:
    app: myapp
spec:
  volumes:
    - name: storage
      emptyDir: {}
  containers:
    - name: myapp-containers
      image: radial/busyboxplus
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: storage
          mountPath: /storage
      command: ['sh', '-c', 'if [ -f /storage/testfile ] ; then touch /storage/testfile && sleep 3600 ; fi']
  initContainers:
    - name: init-containers
      image: radial/busyboxplus
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: storage
          mountPath: /storage
      command: ['sh', '-c', 'touch /storage/testfile && sleep 10']
