apiVersion: v1
kind: Pod
metadata:
  name: rbd-volume
spec:
  containers:
    - name: ct-rbd
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command: ["sleep", "60000"]
      volumeMounts:
      - name: vol-rbd
        mountPath: /mnt/rbd
  volumes:
    - name: vol-rbd
      rbd:
        monitors:
        - '10.125.224.26:6789'
        pool: k8s
        image: pv
        fsType: ext4
        readOnly: false
        user: admin
        secretRef:
          name: ceph-luminous-admin