apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-sc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: rbd