apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rbd
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/rbd
parameters:
  monitors: 10.125.224.26:6789
  adminId: admin
  adminSecretName: ceph-luminous-admin
  adminSecretNamespace: default
  pool: k8s
  userId: admin
  userSecretName: ceph-luminous-admin
  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"