apiVersion: v1
kind: Pod
metadata:
  name: rbd-sc
spec:
  containers:
  - name: ct-rbd
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sleep", "60000"]
    volumeMounts:
    - name: vol-rbd
      mountPath: /mnt/rbd/
      readOnly: false
  volumes:
  - name: vol-rbd
    persistentVolumeClaim:
      claimName: rbd-sc
