version: '3.3'

services:
  mysql:
    image: mysql:5.7
    volumes:
       - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: wordpress

  wordpress:
    depends_on:
       - mysql
    image: wordpress:4.9.6
    ports:
      - 8091:80
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: P@ssw0rd

volumes:
    mysql:
