version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: wordpressdb
    volumes:
       - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: wordpress

  wordpress:
    depends_on:
       - mysql
    image: wordpress:5.9.3
    container_name: wordpress
    ports:
      - 8090:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpressdb
      WORDPRESS_DB_PASSWORD: P@ssw0rd
    volumes:
      - wordpress:/var/www/html

volumes:
    db:
    wordpress:
