kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephfs
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: ceph.com/cephfs
parameters:
  monitors: 10.125.224.26:6789
  adminId: admin
  adminSecretName: ceph-luminous-admin
  adminSecretNamespace: "cephfs"
