apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-dep-node-port
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: ct-go-server
          image: wukongsun/nginx-ingress-demo-svc4:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-node-port
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8888
      nodePort: 30888

