apiVersion: v1
kind: Pod
metadata:
  name: pod1-host-port
  labels:
    app: webapp
spec:
  containers:
    - name: ct-nginx
      image: nginx:1.9.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          hostPort: 30890