apiVersion: v1
kind: PersistentVolume
metadata:
  name: rbd
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    monitors:
      - '10.125.224.26:6789'
    pool: k8s
    image: pv
    user: admin
    secretRef:
      name: ceph-admin
    fsType: xfs
    imageFormat: "2"
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle