apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: wordpress
spec:
  storageClassName: mysql-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
