apiVersion: v1
kind: ConfigMap
metadata:
  name: cm1
data:
  special.how: very
  special.type: charm

---

apiVersion: v1
kind: Pod
metadata:
  name: cm1-pod-env
spec:
  restartPolicy: Never
  containers:
    - name: ct-debian
      image: debian:latest
      command: [ "/bin/sh", "-c", "env && sleep 3000" ]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: cm1
              key: special.how
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: cm1
              key: special.type