apiVersion: v1
kind: Pod
metadata:
  name: vol2-pod-hostpath
spec:
  volumes:
  - name: vol-data
    hostPath:
      path: /Users/ruan/workspace/k8s/20_objects/20_storage
      type: Directory

  restartPolicy: Never
  containers:
  - name: ct-busybox
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: vol-data
      mountPath: /data
    command: ["/bin/sh", "-c", "ls /data & sleep 3000"]
