apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: pvc1-pod
spec:
  volumes:
    - name: vol-data
      persistentVolumeClaim:
        claimName: pvc1
  containers:
    - name: ct-busybox
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "touch /data/xxx & sleep 60000"]
      volumeMounts:
        - name: vol-data
          mountPath: /data
          readOnly: false
