apiVersion: v1
kind: Pod
metadata:
  name: cm5-pod-env
spec:
  restartPolicy: Never
  containers:
    - name: ct-busybox
      image: radial/busyboxplus
      imagePullPolicy: IfNotPresent
      command: [ '/bin/sh', '-c', 'env && sleep 1000000' ]
      envFrom:
        - configMapRef:
            name: cm1
