apiVersion: v1
kind: Pod
metadata:
  name: cm7-pod-vol
spec:
  restartPolicy: Never
  containers:
    - name: ct-busybox
      image: radial/busyboxplus
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh", "-c", "sleep 3000" ]
      volumeMounts:
      - name: config-vol
        mountPath: /etc/config
  volumes:
    - name: config-vol
      configMap:
        name: cm1