apiVersion: v1
kind: Pod
metadata:
  name: pvc1-pod
spec:
  containers:
  - name: ct-busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "sleep 60000"]
    volumeMounts:
    - name: vol-data
      mountPath: /data
      readOnly: false
  volumes:
  - name: vol-data
    persistentVolumeClaim:
      claimName: pvc1
