apiVersion: v1
kind: Pod
metadata:
  name: secret2-pod-env
spec:
  containers:
    - name: ct-busybox
      image: radial/busyboxplus
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh", "-c", "env && sleep 1000000"]
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret2
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret2
              key: password