apiVersion: v1
kind: Pod
metadata:
  name: vol1-emptydir
spec:
  restartPolicy: Never
  volumes:
  - name: vol-data
    emptyDir: {}

  containers:
  - name: ct-busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: vol-data
      mountPath: /data
    command: ['/bin/sh', '-c', 'sleep 3000']