apiVersion: v1
kind: Pod
metadata:
  name: vol2-hostpath
spec:
  restartPolicy: Never
  volumes:
  - name: vol-data
    hostPath:
      path: /tmp
      type: Directory

  containers:
  - name: ct-busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: vol-data
      mountPath: /data
    command: ['/bin/sh', '-c', 'sleep 3000']